name: CI from External Webhook

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  external-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout external repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.client_payload.repository }}
        ref: ${{ github.event.client_payload.branch }}
        token: ${{ secrets.PERSONAL_TOKEN }}
        path: source-code

    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake cppcheck gcovr

    - name: Build project
      run: |
        cd source-code
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd source-code/build
        ctest --output-on-failure

    - name: Run cppcheck
      run: |
        cppcheck source-code --enable=all --inconclusive --quiet --std=c++17

    - name: Deploy
      run: |
        echo "🚀 배포 스크립트 실행!"
